#!/bin/bash
wget http://windelin:12001/erp5/web_site_module/wendelin/dygraph.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_erp5_graph.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_graph.html
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_listbox.html
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_listbox.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin.html
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_show.html
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_show.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_upload.html
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_wendelin_upload.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_erp5_graph.css
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_jio.html
wget http://windelin:12001/erp5/web_site_module/wendelin/jiodev.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_jio.js
wget http://windelin:12001/erp5/web_site_module/wendelin/rsvp.js
wget http://windelin:12001/erp5/web_site_module/wendelin/renderjs.js
wget http://windelin:12001/erp5/web_site_module/wendelin/handlebars.js
wget http://windelin:12001/erp5/web_site_module/wendelin/gadget_global.js
wget http://windelin:12001/erp5/web_site_module/wendelin/jquerymobile.css
wget http://windelin:12001/erp5/web_site_module/wendelin/jquerymobile.js
wget http://windelin:12001/erp5/web_site_module/wendelin/jquery.js

